# Generated by Django 3.1.1 on 2021-03-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210315_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='mentor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
